# Generated by Django 4.2.2 on 2023-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='na', max_length=50),
            preserve_default=False,
        ),
    ]
