# Generated by Django 4.2.2 on 2023-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_blood_group_alter_patient_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
