# Generated by Django 4.2.2 on 2023-07-04 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DiabetesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient')),
            ],
        ),
    ]
