# Generated by Django 4.2.2 on 2023-07-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patient_age_patient_gender_diabetesanalytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiabetesAnalytics',
            new_name='DiabetesAnalysis',
        ),
    ]
