# Generated by Django 4.2.2 on 2023-07-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_diabetesanalytics_diabetesanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesanalysis',
            name='outcome',
            field=models.IntegerField(null=True),
        ),
    ]
