# Generated by Django 4.2.2 on 2023-07-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_diabetesanalysis_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
