# Generated by Django 4.2.2 on 2023-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_patient_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
